### ISSUE TITLE
Duplicate package name

### ISSUE THREAD

**Issue by sjgknight** [massimoaria/openalexR#10]
I've maybe missed something, but I was looking for an easy way to pass a list of author identifiers, and get works. I can see how to get the counts of works, lots of author details, and to get works given a work identifier, but not this.

In looking for the lazy solution (to save me writing queries), there is another package https://github.com/ekmaloney/openalexR which does indeed have this function. I wonder if the packages could be usefully merged or/and one renamed? Having just tried to run both (or rename post install)...it's not as easy as I'd hoped.

Thanks for the great package, it's incredibly useful and so much better to have open data than be reliant on commercial tools.

**Comment by trangdata** [comment]
Hi @sjgknight thank you for this question!

We indeed have a way to do this. Say, we want to find works by the two following authors whose openalex ids we know:
``` r
works_from_author_ids <- oa_fetch(
  entity = "works",
  author.id = c("A923435168", "A2208157607"),
  verbose = TRUE
)
```
The current documentation we have on this is not super clear (one would have to follow the [link](https://docs.openalex.org/api/get-lists-of-entities/filter-entity-lists#works-attribute-filters) to see all the attributes to filter works/). I will work on adding this common use case! Thanks again for the suggestion!

Hope this answers your question!

**Comment by trangdata** [comment]
I should clarify that this option is available only in the development version of the package:
``` r
# install.packages("remotes")
remotes::install_github("massimoaria/openalexR")
```

**Comment by trangdata** [comment]
Another filter attribute we can utilize is authorships.author.orcid/author.orcid. However, we need to make sure that we give the filter the full orcid links with "https://orcid.org/".

``` r
orcids <- c("0000-0003-3737-6565", "0000-0002-8517-9411")
canonical_orcids <- paste0("https://orcid.org/", orcids)
works_from_author_orcids <- oa_fetch(
  entity = "works",
  author.orcid = canonical_orcids,
  verbose = TRUE
)

```

**Comment by sjgknight** [comment]
@Trangdata brilliant, thanks so much! That works perfectly, and means I can reproduce things from the other package without having to install both (phew).  Minor thing, and not sure if the typo is in openalex or openalexR, but unnested concept level is: 'concept_concept_lecel'

**Comment by trangdata** [comment]
@sjgknight Ah yes I did notice the typo. I'm working on a [refine branch](https://github.com/massimoaria/openalexR/tree/refine) that will address this issue (we will no longer rename these columns) to make the package more robust. Hopefully, we'll get to roll out the next cran release soon to incorporate all these changes. Thank you for bearing with us and being such a 🌟  supporter of the package! 🙏🏽
