### ISSUE TITLE
Automatic batching in oa_fetch filters

### ISSUE THREAD

**Issue by trangdata** [massimoaria/openalexR#18]
Currently, openalex allows [50 entities](https://docs.openalex.org/api/get-lists-of-entities/filter-entity-lists#logical-expressions) to be combined in a query. So the following gives an API error when `my_dois` has more than 50 components.
``` r
oa_fetch(
  doi = my_dois,
  entity = "works"
)
```

It may be nice if `oa_fetch` automatically batches these entities if more than 50 entities in the filter are requested.

**Comment by massimoaria** [comment]
You are right.
I have just added a commit that overcomes the limitation of 50 identifiers at a time.
Moreover, I also added the possibility to use doi URLs instead of OpenAlex ids as identifiers

**Comment by trangdata** [comment]
Let's continue [this conversation](https://github.com/massimoaria/openalexR/commit/065cda024fd42c5860cce30209d5dedc9499f1c1#r85621654) here for easier tracking of the issue.

I think 8cd1aca277c8bdf4564f6e99d1c5dda13141e2f1 is okay, but I would like to generalize this for other external IDs as well (not just for works). And perhaps other type of filters. I'll submit a PR for this soon. Maybe you can review? @massimoaria

**Comment by massimoaria** [comment]
> Let's continue [this conversation](https://github.com/massimoaria/openalexR/commit/065cda024fd42c5860cce30209d5dedc9499f1c1#r85621654) here for easier tracking of the issue.
> 
> I think [8cd1aca](https://github.com/massimoaria/openalexR/commit/8cd1aca277c8bdf4564f6e99d1c5dda13141e2f1) is okay, but I would like to generalize this for other external IDs as well (not just for works). And perhaps other type of filters. I'll submit a PR for this soon. Maybe you can review? @massimoaria

Yes of course!
