### ISSUE TITLE
Use codecov

### ISSUE THREAD

**Issue by trangdata** [massimoaria/openalexR#25]
@massimoaria Since you're the admin of the repo, could you follow [this instruction](https://www.r-bloggers.com/2017/06/how-to-add-code-coverage-codecov-to-your-r-package/) to add code coverage to our package, please? 🌻 🌈 

Starting at the step "_Now log in to [codecov.io](https://codecov.io/gh) using the GitHub account._"

**Comment by massimoaria** [comment]
@trangdata Ok, I did it. 
I sent you by email the codecov token to complete the CI environment configuration.

**Comment by trangdata** [comment]
Awesome! Thank you! Now we just need to write more tests to improve that coverage 😅
