### ISSUE TITLE
oaApiRequest with throw an error if query url doesn't have initial parameters

### ISSUE THREAD

**Issue by Shea-Fyffe** [massimoaria/openalexR#3]
Hi Massimo! Thanks for all your great work on this.

I noticed two things in the `oaApiRequest` source code that will lead to a 404 error. First, [Line 155](https://github.com/massimoaria/openalexR/blob/143423091d9f52ca621927f7dcc9c8e8483f9ece/R/oaApiRequest.R#L155) assumes that a query parameter has already been passed by leading with an `&`. The user could work around this by adding a mailto = argument, but on [Line 147](https://github.com/massimoaria/openalexR/blob/143423091d9f52ca621927f7dcc9c8e8483f9ece/R/oaApiRequest.R#L147) the string is never appended because reassignment doesn't occur.

The first issue is always difficult because you never know what the user will pass. Maybe you could take care of this using grepl and a regex pattern? Then moving the "cursor=*" before the mailto given that it is a constant.

```r
oaApiRequest <- function(query_url,
                         total.count = FALSE,
                         mailto = NULL,
                         verbose = FALSE) {
    
    ua <- httr::user_agent(cfg()$user_agent)
    
    ## >> ---- suggestion
    query_anchor <-
        ifelse(grepl("+[^?#]+\\?[^#:]+", query_url), "&", "?")
    
    query_url <- paste0(query_url, query_anchor, "cursor=*")
   ## End suggestion ---- << 

    if (!is.null(mailto)) {
        if (isValidEmail(mailto)) {
            ## >> Then this would change
            query_url <- paste0(query_url, "&mailto:", mailto)
        } else {
            message(mailto, " is not a valid email address")
        }
    }
    
    if (verbose == TRUE) {
        message("Requesting url: ", query_url)
    }
    
    res <- oa_request(query_url, ua)
    
# ...
}
```

Another suggestion might be to not hardcode the user agent and let Rcurl take care of it. If this package gets really popular OpenAlex could flag that UA because so many people are using it.

```r
cfg <- function(.ua =  base::getOption("HTTPUserAgent")) {
    ##>> maybe something like this
    if (is.null(.ua) || length(.ua) == 0L) {
        .ua <-
            paste0(
                "curl/",
                curl::curl_version()[[1]],
                " RCurl/",
                packageVersion("RCurl"),
                " httr/",
                packageVersion("httr")
            )
    }
    
    res <- list(user_agent = .ua)
    
    if (Sys.getenv("OPENALEX_USERAGENT") != "") {
        res$user_agent <- Sys.getenv("OPENALEX_USERAGENT")
    }
  return (res)
}
```

**Comment by massimoaria** [comment]
Thanks for your advice and remarks.
I adopted some of your code rows and solved anchor issues.

**Comment by Shea-Fyffe** [comment]
Thank you @massimoaria!
