### ISSUE TITLE
Package webpage

### ISSUE THREAD

**Issue by trangdata** [massimoaria/openalexR#4]
Hi @massimoaria thank you for a great package! 🚀 

I'm learning more about OpenAlex and would love to contribute to your package while I'm learning. Would you be open to that? I can help make a webpage for your package and standardize some aspects such as tests, LICENSE, or creating a README.Rmd (which would allow for automatic syntax highlighting).

Let me know what you think! Again, awesome work!!! 💯

**Comment by trangdata** [comment]
Closing since I realized that the package has a GPL-3 license.

**Comment by massimoaria** [comment]
Hi,
I am open to collaborating with you to improve the package. We can change the license type to allow that.
Let me know.

**Comment by trangdata** [comment]
Hi @massimoaria Thank you so much for being open to this. I generally work with MIT license file, so if you're okay with that, that would be wonderful! I can help add this info as well.

The process of relicensing would be straightforward since you have been the sole developer so far.
https://r-pkgs.org/license.html#relicensing

**Comment by massimoaria** [comment]
Hi @trangdata thanks for your support in this work.
I have just merged your commits to the main branch and changed the license to MIT.
I have also resolved some conflicts between the main version and your commits.

**Comment by trangdata** [comment]
Thank you so much for being open to the suggestions and contributions @massimoaria! 🙏🏽  I'm wondering if you could add me as collaborator in this repo's Settings. That would make it easier for me to submit PRs and add you as a reviewer. 🌱

**Comment by massimoaria** [comment]
Ok I was able to do it. You should have received an invitation by email as a package collaborator.

**Comment by trangdata** [comment]
Awesome! Accepted!
