### ISSUE TITLE
Filtering with logical expressions

### ISSUE THREAD

**Issue by mamendoza1** [massimoaria/openalexR#40]
Thanks so much for creating this package. It's been so helpful for my research!

I think it would be helpful to add documentation/functionality on how to use logical expressions (AND, OR, NOT) with `oa_query` and`oa_fetch`, in line with the OpenAlex documentation here: https://docs.openalex.org/api/get-lists-of-entities/filter-entity-lists#logical-expressions

**Comment by trangdata** [comment]
Hi @mamendoza1 thank you for your feedback 🌱. Would it be something similar to [this example](https://github.com/massimoaria/openalexR#works) in the readme:

``` r
oa_fetch(
  entity = "works",
  title.search = c("bibliometric analysis", "science mapping"),
  cited_by_count = ">50",
  from_publication_date = "2020-01-01",
  to_publication_date = "2021-12-31",
  sort = "cited_by_count:desc",
  verbose = TRUE
) %>%
  show_works() %>%
  knitr::kable()
#> Requesting url: https://api.openalex.org/works?filter=title.search%3Abibliometric%20analysis%7Cscience%20mapping%2Ccited_by_count%3A%3E50%2Cfrom_publication_date%3A2020-01-01%2Cto_publication_date%3A2021-12-31&sort=cited_by_count%3Adesc
#> Getting 1 page of results with a total of 41 records...
```

As you can see in the verbose output, this is equivalent to the query https://api.openalex.org/works?filter=title.search:bibliometric%20analysis|science%20mapping,cited_by_count:>50,from_publication_date:2020-01-01,to_publication_date:2021-12-31&sort=cited_by_count:desc

Do you think we should also point to the OpenAlex docs on [logical expressions](https://docs.openalex.org/api/get-lists-of-entities/filter-entity-lists#logical-expressions)? My reasoning for not adding this right in the readme is to avoid overwhelming the user with too many low-level OpenAlex syntax doc, but if you think it's helpful, I can add.

**Comment by mamendoza1** [comment]
Hi @trangdata, your example above is useful, but I do think it would be helpful to elaborate a bit more on how to construct more complex queries. I had trouble understanding how to use different logical expressions within the `oa_fetch` commands. For example, in your example above, I initially wondered how to change the `title.search` to say, search `("bibliometric analysis" OR "science mapping") AND "COVID-19"`

My current approach for constructing queries is an attempt to break down `oa_fetch`:

1. Write out the query URL, in line with the OpenAlex documentation on logical expressions. This allows me to customize the query beyond what I could understand in `oa_fetch`. For example:

`https://api.openalex.org/works?filter=title.search:bibliometric analysis|science mapping,title.search:covid-19,cited_by_count:>50,from_publication_date:2020-01-01,to_publication_date:2021-12-31&sort=cited_by_count:desc`

2. Then percent-encode my query using `URLencode`, resulting in

`https://api.openalex.org/works?filter=title.search:bibliometric%20analysis%7Cscience%20mapping,title.search:covid-19,cited_by_count:%3E50,from_publication_date:2020-01-01,to_publication_date:2021-12-31&sort=cited_by_count:desc`

3. Call `oa_request` on the percent-encoded query. Then use `oa2df` to convert the results to a data frame.

I'm not sure if there's a more straightforward approach.

**Comment by trangdata** [comment]
@mamendoza1 Thank you for clarifying your use case.

Interestingly enough, this works:

``` r
library(openalexR)

oa_fetch(
  entity = "works",
  title.search = c("bibliometric analysis", "science mapping"),
  title.search = "covid-19",
  cited_by_count = ">50",
  from_publication_date = "2020-01-01",
  to_publication_date = "2021-12-31",
  sort = "cited_by_count:desc",
  verbose = TRUE
)
#> Requesting url: https://api.openalex.org/works?filter=title.search%3Abibliometric%20analysis%7Cscience%20mapping%2Ctitle.search%3Acovid-19%2Ccited_by_count%3A%3E50%2Cfrom_publication_date%3A2020-01-01%2Cto_publication_date%3A2021-12-31&sort=cited_by_count%3Adesc
#> Getting 1 page of results with a total of 8 records...
#> # A tibble: 8 × 28
#>   id        displ…¹ author ab    publi…² relev…³ so    so_id publi…⁴ issn  url  
#>   <chr>     <chr>   <list> <lgl> <chr>   <lgl>   <chr> <chr> <chr>   <lis> <chr>
#> 1 https://… Invest… <df>   NA    2020-0… NA      Jour… http… Elsevi… <chr> http…
#> 2 https://… A Bibl… <df>   NA    2020-0… NA      Cure… http… Cureus… <chr> http…
#> 3 https://… A bibl… <df>   NA    2020-0… NA      Anna… http… AME Pu… <chr> http…
#> 4 https://… Mappin… <df>   NA    2020-0… NA      BMC … http… Spring… <chr> http…
#> 5 https://… A Bibl… <df>   NA    2020-1… NA      Sust… http… MDPI AG <chr> http…
#> 6 https://… Corona… <df>   NA    2020-0… NA      in V… http… Antica… <chr> http…
#> 7 https://… Biblio… <df>   NA    2020-0… NA      Fron… http… Fronti… <chr> http…
#> 8 https://… COVID-… <df>   NA    2020-0… NA      Anna… http… AME Pu… <chr> http…
#> # … with 17 more variables: first_page <chr>, last_page <chr>, volume <chr>,
#> #   issue <chr>, is_oa <lgl>, cited_by_count <int>, counts_by_year <list>,
#> #   publication_year <int>, cited_by_api_url <chr>, ids <list>, doi <chr>,
#> #   type <chr>, referenced_works <list>, related_works <list>,
#> #   is_paratext <lgl>, is_retracted <lgl>, concepts <list>, and abbreviated
#> #   variable names ¹​display_name, ²​publication_date, ³​relevance_score,
#> #   ⁴​publisher
```

<sup>Created on 2022-11-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Note the use of the `title.search` argument twice in the call. I expected R to complain, but it didn't! 🙈 

Anyhow, I'll add this to the documentation, perhaps a separate vignette on logical expressions. Please let me know if you have other helpful use cases. Also, PRs are most welcome!

**Comment by ar0berts** [comment]
The answer to the logical query question is explained [here](https://docs.openalex.org/how-to-use-the-api/get-lists-of-entities/search-entities#boolean-searches) in the OpenAlex.org documentation.

To produce this in openalexR do this:

```
query1 <- oa_fetch(
  entity = "works",
  title.search = "(EPR OR EHR) NOT usability",
  from_publication_date = "2024-01-01",
  to_publication_date = "2024-08-29",
  count_only = TRUE
)
```
```
query2 <- oa_fetch(
  entity = "works",
  title.search = "(EPR OR EHR) AND usability",
  from_publication_date = "2024-01-01",
  to_publication_date = "2024-08-29",
  count_only = TRUE
)
```
```
query3 <- oa_fetch(
  entity = "works",
  title.search = "(EPR OR EHR)",
  from_publication_date = "2024-01-01",
  to_publication_date = "2024-08-29",
  count_only = TRUE
)
```
giving 
query1 - 532 hits
query2 - 94 hits
query3 - 626 hits
