### ISSUE TITLE
Use OR syntax for bulk query

### ISSUE THREAD

**Issue by trangdata** [massimoaria/openalexR#6]
I can be mistaken, but I don't think we're utilizing the [OR syntax](https://docs.openalex.org/api/get-lists-of-entities/filter-entity-lists#addition-or) to allow for bulk querying with a list of IDs. This would be a nice enhancement feature.

https://docs.openalex.org/api#rate-limits

**Comment by massimoaria** [comment]
Yes, you are right. 
I will add this feature.

**Comment by trangdata** [comment]
I'm happy to help with this as well if you'd like that.

**Comment by trangdata** [comment]
Addressed in #7
