### ISSUE TITLE
Add June as a contributor

### ISSUE THREAD

**Issue by trangdata** [massimoaria/openalexR#70]
Hi @yjunechoe! Thank you so much for your recent significant contributions. 🙌🏽  Would you like to add yourself as a contributor in the DESCRIPTION file? 🪴 

https://journal.r-project.org/archive/2012-1/RJournal_2012-1_Hornik~et~al.pdf

**Comment by yjunechoe** [comment]
Thank you! And yes I'd be happy to - I'll make a PR!
