### ISSUE TITLE
oa_fetch order of arguments

### ISSUE THREAD

**Issue by trangdata** [massimoaria/openalexR#72]
I came across this when revising the package for ropensci. Curious to hear what you think @massimoaria @yjunechoe. 🌈 

Small change, but I was thinking of switching the position of `entity` and `identifier` in `oa_fetch`. https://github.com/massimoaria/openalexR/blob/33bb462c773dc2e091336f9a4dd284fedf3bcefc/R/oa_fetch.R#L58-L59
I think it would be natural to write `oa_fetch("works", ...)` without having to specify `entity = `. Plus, the `identifier` argument is very rarely used in most cases. I don't think this will affect the behavior of the function that much but will allow us to write the query a little faster from now on.

Let me know what you think.

**Comment by massimoaria** [comment]
I agree with you. Reversing the arguments makes using oa_fetch much easier by passing "work" or "author" etc. without specifying entity=.

In other words, I like it.
